name: CI
on:
  push:
    branches: [ master ]
jobs:
  build-example:
    runs-on: ubuntu-latest
    container:
      image: python:3

    steps:
      - name: Install platformio
        run: pip install platformio
      - name: build example app
        run: |
          cd example
          pio run

